# SPDX-FileCopyrightText: 2024 O21 contributors <https://github.com/ForNeVeR/O21>
#
# SPDX-License-Identifier: MIT

name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'

  workflow_dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: 'macos'
            image: 'macos-12'
          - name: 'linux'
            image: 'ubuntu-22.04'
          - name: 'windows'
            image: 'windows-2022'

    name: main.${{ matrix.config.name }}
    runs-on: ${{ matrix.config.image }}

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NuGet cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Verify translations
        shell: pwsh
        run: ./Scripts/Verify-Translations.ps1

  licenses:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4
      - name: REUSE license check
        uses: fsfe/reuse-action@v4

  encoding:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Verify encoding
        shell: pwsh
        run: Scripts/Test-Encoding.ps1
